language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t nkagale/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true nkagale/react-test npm test -- --coverage

after_success:
    - docker build -t nkagale/multi-client ./client
    - docker build -t nkagale/multi-nginx ./nginx
    - docker build -t nkagale/multi-server ./server
    - docker build -t nkagale/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push nkagale/multi-client
    - docker push nkagale/multi-nginx
    - docker push nkagale/multi-server
    - docker push nkagale/multi-worker